controller_manager:
  ros__parameters:
    update_rate: 30

    # Differential Drive Controller
    diff_cont:
      type: diff_drive_controller/DiffDriveController

    # Joint State Broadcaster
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

# Differential Driver Controller Params
diff_cont:
  ros__parameters:
    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_front_joint', 'left_rear_joint']
    right_wheel_names: ['right_front_joint', 'right_rear_joint']
    wheel_separation: 0.5715
    wheel_radius: 0.0762

    use_stamped_vel: false
